distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.4.0
install_time: "Sun Mar 29 06:23:50 2020"
installation_id: "6533ccc8-5164-451e-918d-e8a7380e1d0c"
rime_version: 1.5.3
update_time: "Sun Jul 26 16:02:04 2020"